title: Insan Ridho
description: Personal site and portfolio
url: "https://insanridho.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown
